name: spider_panel

environment:
  sdk: any

dependencies:
  flutter:
    sdk: any
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.0.0
  jwt_decode: ^0.3.0
  qr_flutter: ^4.1.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  jiffy: ^6.1.0
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.1.0
  permission_handler: ^10.4.3
  flutter_secure_storage: ^9.0.0
  
  # For XUI panel integration
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    
  fonts:
    - family: Star2
      fonts:
        - asset: assets/fonts/Star2.ttf

